// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ChooseOutput(arg1:string):Promise<string>;

export function DiscoverProfiles(arg1:string):Promise<Array<model.Profile>>;

export function ExportProfiles(arg1:Array<string>,arg2:string,arg3:string,arg4:string):Promise<model.ExportResult>;
