// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseOutput(arg1) {
  return window['go']['main']['App']['ChooseOutput'](arg1);
}

export function DiscoverProfiles(arg1) {
  return window['go']['main']['App']['DiscoverProfiles'](arg1);
}

export function ExportProfiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportProfiles'](arg1, arg2, arg3, arg4);
}
